import React from 'react'
import Collapsible from '../Collapsible/Collapsible'
import './Guide.css'
import { IoCloseSharp } from "react-icons/io5";

const one = <div class="content"> <p>Setup instructions for a Samsung/LG Smart TV</p> <p><strong>Search in your TV for one of the APPs below</strong></p> <p><strong>IPTV Smarters Pro</strong> (select Xtream codes API )</p> <ul> <li>Click on Xtream code API (XC API)</li> <li>Enter your infos : Name, Login, Password and URL.</li> <li>ADD user.</li> </ul> <p><strong>Alternative apps :</strong></p> <ol> <li>DUPLEX play</li> <li>IBO Player</li> <li>Flix IPTV</li> <li>SET IPTV</li> <li>ELK Player</li> <li>Nanomid</li> <li>Smart IPV</li> <li>Smart STB</li> <li>STB Emu</li> </ol> <p>Once you install one of these recommended APPs, You can use the subscription info that you received from us to log in.</p> <p>In case you are facing any issues, please contact our support team on Whatsapp and they will help you set the subscription in your APP.</p> </div>
const two = <div class="content"> <p>1- Download VLC ( Download URL<strong>&nbsp;<a href="https://www.videolan.org/vlc/./" target="_blank" rel="noopener noreferrer">https://www.videolan.org/vlc/./</a></strong>)</p> <p>2 – Open VLC Player</p> <p>3- Go to&nbsp;<strong>Media</strong>&nbsp;-&gt;&nbsp;<strong>Open Network stream.</strong></p> <p>4- &nbsp;Add your Subscription&nbsp;<strong>M3U</strong>&nbsp;URL we sent to you and press play.</p> <p>5-&nbsp;Wait till all the Channels load (this may take some time)</p> <p>6- In case you are facing any issues with M3U loading, please contact our support team on WhatsApp and they will help you set your subscription.</p> </div>
const three = <div class="content"> <p><strong>Please install one of the recommended IOS apps below:</strong></p> <p>IPTV Smarters Pro (select Xtream codes API )</p> <ul> <li>Click on Xtream code API (XC API)</li> <li>Enter your infos : Name, Login, Password and URL.</li> <li>ADD user.</li> </ul> <p><strong>Alternative apps :</strong></p> <ol> <li>GSE IPTV (select Xtream codes API).</li> <li>ELK Player.</li> <li>IPTVX.</li> </ol> <p>Once you install one of these recommended APPs, select Xtream codes API and you can use the subscription info that you received from us to log in.</p> <p>In case you are facing any issues, please contact our support team on WhatsApp and they will help you set the subscription in your APP.</p> </div>
const four = <div class="content"> <p><strong>Go to the Google Play store and look for one of the recommended APP’s below:</strong></p> <p>IPTV Smarters Pro (You may find it under the name&nbsp;smarters player lite)</p> <ul> <li> <ul> <li>Click on Xtream code API (XC API)</li> <li>Enter your infos : Name, Login, Password and URL.</li> <li>ADD user.</li> </ul> </li> </ul> <p><strong>Alternative apps :</strong></p> <ol> <li>DUPLEX play</li> <li>IBO Player</li> <li>Flix IPTV</li> <li>SET IPTV</li> <li>ELK Player</li> <li>Nanomid</li> <li>Smart IPV</li> <li>Smart STB</li> <li>STB Emu</li> </ol> <p>Once you install one of these recommended APPs, You can use the subscription info that you received from us to log in.</p> <p>In case you are facing any issues, please contact our support team on Whatsapp and they will help you set the subscription in your APP.</p> </div>
const six = <div class="content"> <p><b>Connect MAG DEVICE to TV and Internet. Then do as follows</b></p> <ol> <li> <ol> <li>Go to: Settings—&gt; System Settings —&gt; Servers—&gt;Portals</li> <li>Set Portal 1: IPTV Shop</li> <li>Set Portal 1 URL&nbsp;<i>( see your E-mail )</i></li> <li>Set Portal 2 Name&nbsp;<i><u><b>leave this empty</b></u></i>&nbsp;<i>&nbsp;add this only If you order the second subscription</i></li> <li>Set Portal 2 URL&nbsp;<i><u><b>leave this empty</b></u></i>&nbsp;<i>&nbsp;</i><i></i><i>add this only If you order the second subscription</i></li> <li>Save everything</li> <li>Reboot device</li> <li>After the box is restarted, wait until the TV screen shows the channels.</li> </ol> </li> </ol> <p>In case you are facing any issues, please contact our support team on WhatsApp and they will help you set the subscription in your APP.</p> </div>
const seven = <div class="content"> <ul> <li>Install an app named&nbsp;<strong>DOWNLAODER</strong>&nbsp;:&nbsp;<a href="https://www.youtube.com/watch?v=dmPyIoTndbU&amp;t=100s">https://www.youtube.com/watch?v=dmPyIoTndbU&amp;t=100s</a></li> <li><span lang="FR">Open&nbsp;<strong>DOWNLAODER</strong>&nbsp;and install this application :&nbsp;<a href="https://www.iptvsmarters.com/smarters.apk">https://www.iptvsmarters.com/smarters.apk</a></span></li> <li>Click on Xtream code API (XC API)</li> <li>Enter your infos : Name, Login, Password and URL.</li> <li>ADD user.</li> </ul> </div>
const five = <div class="content"> <p><strong>STB Emulator Setup Instructions:</strong></p> <ol> <li>Download ‘STB Emulator’ from the Google Play Store&nbsp;<a href="https://play.google.com/store/apps/details?id=com.mvas.stb.emu.free" target="_blank" rel="noopener noreferrer">here</a>.</li> <li>Install and Load the ‘STB Emulator’ app and you will see your ‘MAC address’ on screen.</li> <li>Tap near the ‘Top right corner’ and then click ‘Settings’ – the 4th icon from the right.</li> <li>Tap ‘Profiles’.</li> <li>Tap ‘Test portal’ to modify the existing profile or ‘Add profile’ to start a new one.</li> <li>Tap ‘STB Model’.</li> <li>Tap ‘MAG 250’ or whichever STB you wish to emulate.</li> <li>Tap ‘Portal settings’.</li> <li>Enter your ‘Portal URL’ (Check your activation e-mail) and click OK.</li> <li>Now tap ‘Screen Resolution’.</li> <li>Choose ‘1280×720’ (You can choose higher with internet speed 16+ Mbps).</li> <li>Exit the app and restart.</li> <li>You will now see your channel list.</li> </ol> <br></br> <p><strong>Troubleshooting STB Emulator</strong></p> <p>If you have any problems viewing the Channels please follow this recommended fix:<br></br>Restart your App, Device/Box, and Wi-Fi Router.</p> <p>&nbsp;</p> <p>In case you are facing any issues, please contact our support team on WhatsApp and they will help you set the subscription in your APP.</p> </div>

const Guide = (props) => {
  return (
      <div className="setup-guide">
        <div className={`trans-overlay ${props.state ? 'show' : ''}`}></div>
        <section className='guide-section'>
            <div className={`guide ${props.state ? 'show' : ''}`}>   
                <IoCloseSharp color='white' size={25} className='close-guide' onClick={props.onclose}/>
                <p className="subheading">Setup Guide</p>
                <h3 className="heading-guide">HOW TO SETUP THE IPTV ACCOUNT ON YOUR DEVICE</h3>
                <Collapsible className='guide_collapsible' toggletitle="Smart TV (Samsung & LG)" toggledescription={one}/>
                <Collapsible className='guide_collapsible' toggletitle="PC/MAC (VLC Software)" toggledescription={two}/>
                <Collapsible className='guide_collapsible' toggletitle="Apple ( iPhone/iPad/Apple TV)" toggledescription={three}/>
                <Collapsible className='guide_collapsible' toggletitle="Android (TV/Box/Phone)" toggledescription={four}/>
                <Collapsible className='guide_collapsible' toggletitle="MAG" toggledescription={five}/>
                <Collapsible className='guide_collapsible' toggletitle="INSTALL IPTV Smarters or other APP ON FIRESTICK" toggledescription={six}/>
            </div>
        </section>
      </div>
  )
}

export default Guide